language: ruby
cache: bundler
rvm:
  - 2.5.3

branches:
  only:
    - master
    - /\d+[.]\d+[.]\d+/

before_install:
  - gem update --system
  - gem install bundler

script: rspec
# jobs:
#   include:
#     # Define the release stage that runs semantic-release
#     - stage: release
#       node_js: lts/*
#       # Advanced: optionally overwrite your default `script` step to skip the tests
#       if: branch = master
#       script: skip
#       deploy:
#         provider: script
#         skip_cleanup: true
#         script:
#           - npx semantic-release
